version: '3.8'
 
services:
 mongo:
  container_name: dockermongodatabase
  image: mongo
  ports:
    - '27017:27017'
  environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password123
